# Generated by Django 4.0 on 2022-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_genres_alter_review_movie_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
